theme = "github_dark"

[editor]
true-color = true

[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "underline"

[keys.normal]
A-down = ["extend_to_line_bounds", "delete_selection", "paste_after"]
A-up = ["extend_to_line_bounds", "delete_selection", "move_line_up", "paste_before"]
A-S-up = "copy_selection_on_prev_line"
A-S-down = "copy_selection_on_next_line"
A-C-up = "copy_selection_on_prev_line"
A-C-down = "copy_selection_on_next_line"
C-home = ":goto 1"
C-end = "goto_file_end"
C-up = "scroll_up"
C-down = "scroll_down"
C-left = "move_prev_word_start"
C-right = "move_next_word_end"
F2 = "rename_symbol"
esc = "keep_primary_selection"
y = "yank_joined_to_clipboard"
tab = "indent"
S-tab = "unindent"
p = "paste_clipboard_after"
P = "paste_clipboard_before"
S-left = "move_prev_word_end"
S-right = "move_next_word_start"

[keys.insert]
S-backspace = "delete_word_backward"
S-left = ["normal_mode", "move_prev_word_end"]
S-right = ["normal_mode", "move_next_word_start"]

[keys.select]
S-left = ["extend_prev_word_end"]
S-right = ["extend_next_word_start"]

